---
# var/lib/awx/venv/awx/lib/python3.9/site-packages/awx/playbooks/project_update.yml
# Perform more testing to figure out why certain downloads are happenning
collections:
  - name: community.general
    source: "https://rhel-9-server.lab.test/api/galaxy/content/community/"
  - name: zjpeterson.aci
    source: "https://rhel-9-server.lab.test/api/galaxy/content/community/"
  - name: elchico2007.chatgpt
    source: "https://rhel-9-server.lab.test/api/galaxy/content/community/"
