---
# var/lib/awx/venv/awx/lib/python3.9/site-packages/awx/playbooks/project_update.yml
# Perform more testing to figure out why certain downloads are happenning
collections:
  - name: community.general
    version: 5.7.0
  - name: zjpeterson.aci
    version: 0.3.1