- name: Get ios Facts
  cisco.ios.ios_facts:
    gather_subset: interfaces
  when: ansible_network_os == 'cisco.ios.ios'

- name: PUT interfaces
  ansible.builtin.uri:
    url: https://rhel-9.lab.test:443/api/v2/hosts/3/variable_data/
    user: admin
    password: "{{ aap_password }}"
    method: PUT
    body: "{{ ansible_facts['net_interfaces'] }}"
    force_basic_auth: yes
    status_code: 200
    validate_certs: false
    body_format: json