---
# tasks file for roles/networking-dns
- name: Pull DNS config
  ansible.builtin.include_tasks: "{{ group_names.0 }}/gather_dns.yml"

- name: Implementation
  ansible.builtin.include_tasks: "{{ group_names.0 }}/implement_dns.yml"