---
- name: Update Change ticket
  hosts: localhost
  gather_facts: no

  tasks:  
    - name: Close change_request
      servicenow.itsm.change_request:
        state: closed
        close_code: "successful"
        close_notes: "VM has been provisioned to Infrastructure"
        assignment_group: "Hardware"
        number: "{{ change_request['record']['number'] }}"