---
- name: Update Change ticket
  hosts: "{{ survey_name | default('localhost') }}"
  gather_facts: false

  tasks:  
    - name: Close change_request
      servicenow.itsm.change_request:
        state: closed
        close_code: "successful"
        close_notes: "{{ hostvars['inventory_hostname'] | to_nice_yaml }}"
        assignment_group: "Hardware"
        number: "{{ change_request['record']['number'] }}"