---
- name: Update Change ticket
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Update a change
      servicenow.servicenow.snow_record:
        table: change_request
        state: present
        number: "{{ itsm_change['record']['number'] }}"
        data:
          work_notes : "VM has been provisioned to Infrastructure"
    
    - name: Update a change
      servicenow.servicenow.snow_record:
        table: change_request
        state: present
        number: "{{ itsm_change['record']['number'] }}"
        data:
          work_notes : "Finally Done!"