---
collections:
  - name: cisco.ios
  - name: junipernetworks.junos
  - name: arista.eos
  - name: arubanetworks.aoscx
  - name: community.network
  - name: paloaltonetworks.panos
  - name: elchico2007.chatgpt