---
# Build image using ansible-builder
# push image to remote repo 'podman push <image name> rhel-9-server.lab.test/<image name>:<tag>'
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'rhel-9-server.lab.test/ee-minimal-rhel8:latest'
  EE_BUILDER_IMAGE: 'rhel-9-server.lab.test/ansible-builder-rhel8:latest'
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-certs'

ansible_config: '../ansible.cfg'

dependencies:
  galaxy: galaxy/requirements.yml
  python: python/requirements.txt
  system: system/bindep.txt

additional_build_steps:
  prepend: |
    RUN whoami
    RUN cat /etc/os-release

  append:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc
