---
- name: Extend VM guest disk
  hosts: "{{ host | default('all') }}"
  gather_facts: false

  vars:
    datacenter_name: Datacenter

  tasks:
    - name: Gather disk info from virtual machine using name
      community.vmware.vmware_guest_disk_info:
        datacenter: "{{ datacenter_name }}"
        validate_certs: no
        name: "{{ inventory_hostname }}"
      delegate_to: localhost
      register: disk_info
    
    - debug:
        msg: "{{ disk_info['guest_disk_info']['0']['capacity_in_kb'] | human_readable(unit='G') }}"

    # - name: Connect to VMWare and resize disk on Guest VM
    #   community.vmware.vmware_guest_disk:
    #     datacenter: "{{ datacenter_name }}"
    #     validate_certs: no
    #     name: "{{ inventory_hostname }}"
    #     disk:
    #       - size_mb: 50000
    #         state: present
    #         unit_number: 0
    #         scsi_controller: 0
    #         scsi_type: 'lsilogicsas'
    #   delegate_to: localhost
    #   register: disk_facts