---
- name: Configure Basic interface configuration
  hosts: "{{ survey_name | default('all') }}"
  tasks:
    - name: Configure basic ios interface configuration
      cisco.ios.ios_interfaces:
        config:
        - name: "{{ interface }}"
          description: "{{ description }}"
          enabled: "{{ enabled }}"
          speed: "{{ speed }}"
          mtu: "{{ mtu }}"
        state: replaced
      when: ansible_network_os == 'cisco.ios.ios'
      notify:
        - Upload Interfaces

  handlers:
    - name: Upload Interfaces
      ansible.builtin.include_tasks: handlers/parse_interfaces.yml
