---
- name: Update packages
  hosts: all
  gather_facts: false

  tasks:
    - name: Updating packages to compliant version
      ansible.builtin.dnf:
        name: "{{item.name}}-{{item.version}}*"
        state: present
      when: item.failed
      loop: "{{ artifact }}"
      become: true

