---
- name: Update packages
  hosts: "{{ artifact.server }}"
  gather_facts: false

  tasks:
    - name: Updating packages to compliant version
      ansible.builtin.dnf:
        name: "{{item.package_name}}-{{item.version_needed}}*"
        state: present
      loop: "{{ artifact['non_compliant_packages'] }}"
      when: artifact['server'] == inventory_hostname
      become: true
