---
- name: Get Package Facts
  hosts: all
  gather_facts: false

  tasks:
  - block:
      - name: Ensure package is in compliance
        ansible.builtin.package_facts:
          strategy: all

      - name: Assert linux packages are in compliance
        ansible.builtin.assert:
          that:
            - packages[item.name] is defined
            - packages[item.name][0]['version'] == item.version
          success_msg: "'{{ item.name }}' is compliant"
          fail_msg: "Found Package '{{ item.name }}' with non compliant version '{{ packages[item.name][0]['version'] | default('Not Installed') }}'"
        loop: "{{ compliant_packages }}"
        register: devices_output
    
    always:
      - name: Show packages not in compliance
        ansible.builtin.set_fact:
          non_compliant_packages: "{{ non_compliant_packages | default([]) + [ {'package_name': item.name, 'non_compliant_version': packages[item.name][0]['version'], 'version_needed': item.version } ] }}"
        loop: "{{ compliant_packages }}"
        when: 
          - packages[item.name] is defined
          - packages[item.name][0]['version'] != item.version
      
      - name: Add packages not installed
        ansible.builtin.set_fact:
          non_compliant_packages: "{{ non_compliant_packages | default([]) + [ {'package_name': item.name, 'version_needed': item.version } ] }}"
        loop: "{{ compliant_packages }}"
        when: packages[item.name] is not defined

      - name: Gather Data and package into artifact
        ansible.builtin.set_fact:
          package_facts: "{{ { 'server': inventory_hostname, 'non_compliant_packages': non_compliant_packages } }}"
        when: non_compliant_packages | default([]) | length  >= 1

      - debug:
          var: package_facts
        when: non_compliant_packages | default([]) | length  >= 1

      - name: Aggregating packages_installed stat per host
        ansible.builtin.set_stats:
          data:
            artifact: "{{ package_facts }}"
        when: non_compliant_packages | default([]) | length  >= 1
      
      - name: Aggregating packages_installed stat per host
        ansible.builtin.set_stats:
          data:
            artifact: "{{ package_facts | default('Packages in compliance') }}"
        when: non_compliant_packages | default([]) | length  == 0
