---
- name: Get Firmware Facts
  hosts: networking

  tasks:
    - name: Ensure Firmware is in compliance
      ansible.builtin.assert:
        that:
          - ansible_facts['net_version'] == firmware_version
        fail_msg: "Device is not in compliance for its OS version, version found '{{ansible_facts['net_version']}}' "
        success_msg: "Device is in compliance."
      register: device_failures
      ignore_errors: true
    
    - name: Set fact
      ansible.builtin.set_fact:
        device_failures: "{{ device_failures }}"
      delegate_to: localhost

- name: Get Firmware Facts
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Send Slack Notification
      ansible.builtin.uri:
        url: https://hooks.slack.com/services/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
        method: POST
        body: '{"text": "{{ device_failures | to_nice_yaml }}" }'
        body_format: json
      delegate_to: localhost

