---
- name: Get Firmware Facts
  hosts: all

  tasks:
  - block:
      - name: Ensure Firmware is in compliance
        ansible.builtin.assert:
          that:
            - ansible_facts['net_version'] == firmware_version | default("")
          fail_msg: "Device is not in compliance for its OS version, version found '{{ansible_facts['net_version']}}' "
          success_msg: "Device is in compliance."
        register: devices_output
      
      - name: Set Devices in compliance
        ansible.builtin.set_fact:
          in_compliance: True

    always:
      - name: Parse jinja into report
        ansible.builtin.set_fact:
          firmware_report: "{{ firmware_report | default([]) + [ { 'network_device': inventory_hostname, 'current_version': ansible_facts['net_version'], \
              'compliant_version': firmware_version | default('Null'), 'compliant': in_compliance | default(False) } ] }}"

      - name: Aggregating packages_installed stat per host
        ansible.builtin.set_stats:
          data:
            artifact: "{{ firmware_report }}"
