---
- name: Get Firmware Facts
  hosts: all

  tasks:
  - block:
      - name: Ensure Firmware is in compliance
        ansible.builtin.assert:
          that:
            - ansible_facts['net_version'] == firmware_version
          fail_msg: "Device is not in compliance for its OS version, version found '{{ansible_facts['net_version']}}' "
          success_msg: "Device is in compliance."
        register: devices_output

    always:
      - name: Aggregating packages_installed stat per host
        ansible.builtin.set_stats:
          data:
            artifact: "{{ devices_output }}"
