---
- name: ACI Query Automation Controller
  hosts: all
  connection: local
  gather_facts: false

  vars:
    tenant: ""

  tasks:
  - name: Query Tenant
    cisco.aci.aci_tenant:
      hostname: "{{ inventory_hostname }}"
      username: "{{ lookup('ansible.builtin.env', 'ACI_USERNAME') }}"
      password: "{{ lookup('ansible.builtin.env', 'ACI_PASSWORD') }}"
      validate_certs: false
      state: query
      tenant: "{{ tenant }}"
      output_level: debug
    register: query_result
  
  - name: Show Query Output
    ansible.builtin.debug:
      var: query_result