---
- name: Install Podman and run http container
  hosts: all
  vars:
    exposed_port: ""
  tasks:

    - name: installing docker
      ansible.builtin.package:
        name: "docker"
        state: latest
      become: true

    - name: Pull image
      community.docker.docker_image:
        name: 'docker.io/library/nginx'
        pull: true
        tag: latest
      become: true

    - name: Copying file into home
      ansible.builtin.template:
        src: ../templates/index.j2
        dest: /tmp/index.html
        mode: 0777
        owner: root
        group: root
      become: true

    - name: Re-create a redis container
      community.docker.docker_container:
        name: webserver
        image: 'docker.io/library/nginx'
        state: started
        detach: true
        expose:
          - "{{ exposed_port }}"
        ports:
          - "{{ exposed_port }}:80"
        volumes: /tmp/:/usr/share/nginx/html/

  handlers:
      - name: Start Podman
        ansible.builtin.service:
          name: "podman"
          enabled: true
          state: started