---
- name: Install Podman and run http container
  hosts: all
  vars:
    exposed_port: ""
  tasks:

    - name: installing podman
      ansible.builtin.package:
        name: "podman"
        state: latest

    - name: Pull image
      containers.podman.podman_image:
        name: httpd
        pull: true
        tag: latest

    - name: Copying file into home
      ansible.builtin.copy:
        src: ../templates/index.j2
        dest: /home/luvalle/index.html
        mode: 0777
        user: luvalle
        group: luvalle

    - name: Re-create a redis container
      containers.podman.podman_container:
        name: webserver
        image: httpd
        state: started
        detach: true
        expose:
          - "{{ exposed_port }}"
        ports:
          - "{{ exposed_port }}:80"
        volumes: /home/luvalle/:/usr/local/apache2/htdocs/:exec

  handlers:
      - name: Start Podman
        ansible.builtin.service:
          name: "podman"
          enabled: true
          state: started