---
- name: Install Podman and run Apache container
  hosts: all
  gather_facts: false
  vars:
    exposed_port: ""
    webserver_msg: ""
  tasks:
    - name: installing podman
      ansible.builtin.package:
        name: "podman"
        state: latest
      become: true

    - name: Pull image
      containers.podman.podman_image:
        name: 'docker.io/library/nginx'
        pull: true
        tag: latest
      become: true

    - name: Copying file into tmp
      ansible.builtin.template:
        src: ../templates/index.j2
        dest: /tmp/index.html
        mode: 0777

    - name: Re-create a redis container
      containers.podman.podman_container:
        name: httpd_webserver
        image: 'docker.io/library/nginx'
        state: started
        detach: true
        expose:
          - "{{ exposed_port }}"
        ports:
          - "{{ exposed_port }}:80"
    
    - name: Sending html file
      ansible.builtin.command: 'podman cp /tmp/index.html httpd_webserver:/usr/share/nginx/html'
    
    - name: Display url
      ansible.builtin.debug:
        msg: "http://{{inventory_hostname}}:{{exposed_port}}"
    
    - name: Create Artifact
      ansible.builtin.set_fact:
        artifact: "apache container spun up, please visit 'http://{{inventory_hostname}}:{{exposed_port}}' to access your site."
      
    - name: Send notification message via Slack
      community.general.slack:
        token: '{{ slack_token }}'
        msg: '{{ artifact | default("Null") }}'
        
  handlers:
      - name: Start Podman
        ansible.builtin.service:
          name: "podman"
          enabled: true
          state: started