---
- name: Send Slack Notification
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Send notification message via Slack
      community.general.slack:
        token: '{{ slack_token }}'
        msg: '{{ artifact | default("Packages in compliance") | to_nice_yaml }}'