- name: Deploy EC2 instance using terraform
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Using Custom Variables
      community.general.terraform:
        project_path: '../project'
        state: present
        variables:
          name: "{{ survey_name }}"
          ami: ami-0a1a70369f0fce06a
          instance_type: "{{ survey_instance_type }}"
          security_group: "sg-00d8298aff171d8d0"
        force_init: true