- name: test
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
     - azure.azcollection
     - community.general
     - community.general.random_pet
     - community.general.random_string
     - community.general.random_words

  tasks:
######################################## Create RG #########################################

   - name: Generate pet name no word number
     tags: pet
     set_fact:
       az_rg: "{{ lookup('community.general.random_pet') }}"

   - name: Print
     debug:
        msg: '{{ az_rg }}'
