- name: Remove EC2 instance if failure
  hosts: "{{ survey_name }}"
  gather_facts: false

  tasks:
    - name: Remove Instance
      amazon.aws.ec2_instance:
        state: terminated
        region: "us-west-1"
        instance_ids:
          - "{{ instance_id }}"
      delegate_to: localhost