- name: Check Application State
  hosts: "{{ survey_name }}"

  tasks:
    - name: Check that you can connect (GET) to a page and it returns a status 200
      ansible.builtin.uri:
        url: "http://{{ ansible_host }}:80"