- name: Add Administrator group to manage system
  hosts: "{{ survey_name }}"

  tasks:
    - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: johnd
        comment: John Doe
        uid: 1040
        group: admin
    
    - name: Add the user 'jamesd' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: jamesd
        comment: James Dow
        uid: 1041
        group: admin

