---
- name: Install Windows Security updates
  hosts: all
  gather_facts: false

  tasks:

    - name: Install all security, critical, and rollup updates without a scheduled task
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates