---
- name: Extend Windows Disk
  hosts: "{{ host + '.lab.test' | default('all') }}"
  gather_facts: false

  vars:
    datacenter_name: Datacenter
  
  tasks:
    - name: Wait 300 seconds, but only start checking after 15 seconds
      wait_for_connection:
        delay: 15
        timeout: 300

    - name: Extend Partition
      win_partition:
        disk_number: 0
        partition_number: 1
        size: "{{ disk_info.partitions[1].size_max }}"
        extend: yes